# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: windows-2019

  jobs:
    - job: ATL Agent Job
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'ATLpom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          testRunTitle: 'ATL Smoke Test Results'
          goals: 'package'

    - job: LVM Agent Job
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'LVMpom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          testRunTitle: 'LVM Smoke Test Results'
          goals: 'package'
    
    - job: AMC Agent Job
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'AMCpom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          testRunTitle: 'AMC Smoke Test Results'
          goals: 'package'
    
    - job: ATL App Agent Job
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'ATLApppom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          testRunTitle: 'ATL App Smoke Test Results'
          goals: 'package'
    
    - job: EXP Agent Job
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'EXP pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          testRunTitle: 'EXP Smoke Test Results'
          goals: 'package'
    
    - job: Sitecore Agent Job
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'Sitecorepom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          testRunTitle: 'Sitecore Smoke Test Results'
          goals: 'package'
